### ISSUE TITLE
Bits of history we've found and grafted on

### ISSUE THREAD

**Issue by wking** [swcarpentry/shell-novice#2]
This is a meta issue for laying out which history we've found for bc's `novice/shell`, and whether or not it's been grafted into this repository's `master` branch:
- [x] everything from swcarpentry/bc under the `novice/shell` name (since swcarpentry/bc@b8c7dc3 (Reorganizing material to put novice + intermediate at top level, 2014-02-16), see swcarpentry/bc#812 for commands used).
- [x] everything from swcarpentry/bc under the `shell/novice` name (after swcarpentry/bc@3a38907 (shell: Rename the new-style lessons from 'bash' to 'shell', 2014-01-09, swcarpentry/bc#222), but before swcarpentry/bc@b8c7dc3, see #3 for commands used).
- [x] everything from swcarpentry/bc under the `bash/novice` name (before swcarpentry/bc@3a38907, see #4 for commands used).
- [x] the `gen-*.py` scripts which were dropped by the filter-branch in #4 (see #13 for commands used).
- [ ] any copy-paste commits there, if it wasn't all from scratch.  Mention them (or sections of history that you know were from scratch) and I'll add them to this list.
- [x] cleanup commit-message formatting for long commits like swcarpentry/bc@5705090 (Getting rid of old cheat sheets …, 2014-02-27, see #9 for commands used).
- [ ] remove auto-generated content
- [ ] track down sources for downloaded content (see #14).
- [x] Add `novice/ref/01-shell.md` and `novice/teaching/02-shell.md` (see #27 for commands used).
