### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/shell-novice#961]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [ ] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by ErinBecker** [comment]
Hi Maintainers! - Just confirming that you're still planning on including your lesson in the June 2019 release. We'll be putting out a blog post tomorrow inviting contributors to work on issues that have been tagged as part of the release milestone, so if there are specific issues you're looking for community help with, please add them to that milestone. I'll make a first pass and add issues currently marked "help-wanted" to the milestone, but please feel free to update the milestone issue list at your convenience. Please let me know if you have any questions!

**Comment by gcapes** [comment]
Hi Erin,
I've checked some of the items - perhaps @swcarpentry/shell-maintainers could look at the remaining items?

**Comment by gdevenyi** [comment]
Thanks @gcapes for checking off a bunch, I'll knock off some more.

**Comment by ErinBecker** [comment]
Hey Maintainers - just checking in to see if you're still planning on joining the release this month. We're asking that all lessons have completed the checklist by [Tuesday, 4 June, Anywhere on Earth time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20190604T235959&p1=3399) in order to be included in the release. Please let me and @fmichonneau know if you have any questions or are running into any technical issues with preparing your lesson.

**Comment by gcapes** [comment]
Hi Erin,
I think the lesson meets all the criteria but don't have time to check beyond what I've already ticked off. I guess we missed the deadline for this one.

**Comment by gdevenyi** [comment]
I still have time to try and go over the last sets today!

**Comment by fmichonneau** [comment]
don't worry about checking the links, I'll do that before minting the release. Double checking that the code and the output match is the most useful at this time. Thanks!

**Comment by gdevenyi** [comment]
We're good to go!

**Comment by ErinBecker** [comment]
Fantastic! Thanks @gdevenyi.

**Comment by ErinBecker** [comment]
Awesome work @swcarpentry/shell-novice-maintainers  and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
The lesson is released! Unfortunately, there is an issue with the zenodo integration which prevents the automated creation of a DOI for this lesson. I've contacted them and I'm hoping we can get resolved this soon. Thanks for your work on this lesson!

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3266823
